### ISSUE TITLE
Use of OpenAI Logo

### ISSUE THREAD

**Issue by raniabayoumy** [Azure-Samples/openai-end-to-end-baseline#1]
Per OpenAI [INTERIM OPENAI BRAND AND TRADEMARK GUIDELINES](https://microsoft-my.sharepoint.com/:w:/p/camgat/EZ_2wTs7HkZAoVJlA2EWXLUBoEY9LGVZSUnSS18uwH2nlg?e=NWzI9R) we were previously informed NOT to use OAI assets including logo interchangeably to refer to Azure OpenAI service and if needed, to follow approval process highlighted in the Doc.

Please review and make changes to architecture diagrams as needed.

**Comment by ckittel** [comment]
Thanks! This has been resolved, but please keep us honest going forward as well!
