### ISSUE TITLE
Include AI Studio

### ISSUE THREAD

**Issue by mbilalamjad** [Azure-Samples/openai-end-to-end-baseline#17]
With AI Studio being positioned as a hero service, this landing zone implementation should include it instead of ML workspace, my understanding is that under lying it is ML workspace with a Hub parameter which results in it being deployed as AI Studio instead of ML Workspace

**Comment by ckittel** [comment]
Work is being done first in basic implementation. You can follow along at Azure-Samples/openai-end-to-end-basic#19. After that implementation is updated and the Learn article is updated, then we'll be doing a similar migration to the Baseline.

**Comment by ckittel** [comment]
Work is being done now in this repo. You can follow along in the `collab/ai-studio` branch.
