### ISSUE TITLE
Resource Provider Registration

### ISSUE THREAD

**Issue by mbilalamjad** [Azure-Samples/openai-end-to-end-baseline#19]
Required Resource Provider Registration should be listed as an unregistered resource provider like microsoft.insights

**Comment by ckittel** [comment]
Agreed. Let's do this in the "Basic" and then forward-apply to the baseline.

**Comment by ckittel** [comment]
@mbilalamjad can you open a PR to pull in the relevant changes from Azure-Samples/openai-end-to-end-basic#9 into here?
