### ISSUE TITLE
Principal ID variable giving error in spite of it being 36 characters

### ISSUE THREAD

**Issue by Rajani-Janaki-Ram** [Azure-Samples/openai-end-to-end-baseline#32]
The **${PRINCIPAL_ID}** retrieval gives an error in spite of it being 36 characters, the same value being provided inline gives success though. 

RESOURCE_GROUP=rg-chat-baseline-${LOCATION}
az group create -l $LOCATION -n $RESOURCE_GROUP

PRINCIPAL_ID=$(az ad signed-in-user show --query id -o tsv)

az deployment group create -f ./infra-as-code/bicep/main.bicep \
  -g $RESOURCE_GROUP \
  -p appGatewayListenerCertificate=${APP_GATEWAY_LISTENER_CERTIFICATE_APPSERV} \
  -p baseName=${BASE_NAME} \
  -p yourPrincipalId=${PRINCIPAL_ID}
  
  @ckittel

**Comment by ckittel** [comment]
Please execute command `which az` and see if you are getting the following:

> If you're executing this from WSL, be sure the Azure CLI is installed in WSL and is not using the version installed in Windows. which az should show /usr/bin/az.

**Comment by Rajani-Janaki-Ram** [comment]
Error was because of missing the Azure CLIS installation. Fixed now 

- Install the Azure CLI in WSL
curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash

- Verify the installation by checking the Azure CLI version:
az --version

-  Confirm WSL is Using the Correct Azure CLI Installation
which az
This should return /usr/bin/az (or another path in WSL), confirming it’s using the WSL installation.
If it instead returns a Windows path (e.g., /mnt/c/Program Files (x86)/Microsoft SDKs/Azure/CLI2/wbin/az), WSL might be using the Windows-installed Azure CLI version.
